# Generated by Django 2.2.5 on 2020-07-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200713_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
    ]
