# Generated by Django 2.2.5 on 2020-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200708_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
