# Generated by Django 2.2.5 on 2020-07-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
