# Generated by Django 2.2.5 on 2020-07-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200710_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(default='此人很懒,什么也没有留下~', max_length=100, null=True),
        ),
    ]
