# Generated by Django 2.2.5 on 2020-07-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_blog_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_del',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
