# Generated by Django 2.2.5 on 2020-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image1',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='封面图1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='封面图2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='封面图3'),
        ),
    ]
