# Generated by Django 2.2.5 on 2020-07-12 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userfollow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userfollow',
            table='t_user_follow_blog',
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Blog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户博客收藏表',
                'verbose_name_plural': '用户博客收藏表',
                'db_table': 't_user_like_blog',
            },
        ),
    ]
