# Generated by Django 2.2.5 on 2020-07-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200712_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='is_like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
